// SPDX-License-Identifier: MPL-2.0
(() => {
  'use strict';
  const S=window.SentinelApp;
  const {$,state,api,busy,activity,notice,esc,bytes,badge,sev,question,band,empty,ledger,table,primitiveRows,jsonContext,registerLens}=S;

  async function renderReclaim(){busy('Estimating','Cleanup Preview');const d=await api('/api/cleanup/preview');const items=d.items||d.candidates||[];let body=ledger(primitiveRows(d,12));if(items.length){const keys=['name','path','size','reason'].filter(k=>items.some(x=>x[k]!=null));body+=table(keys.map(k=>k),items.slice(0,200).map(x=>keys.map(k=>k==='size'?bytes(x[k]):`<span class="${k==='path'?'mono':''}">${esc(x[k]??'')}</span>`)));}$('#evidenceStage').innerHTML=question()+band(1,'Reviewable estimate',body,'Large, old, cached, or duplicated-looking does not mean disposable.')+band(2,'Safety boundary','<div class="s24-note good">Cleanup Preview does not automatically delete files. Eligible files must move through the separate Safe Change preview and recovery workflow.</div>');activity('Ready',100,'Cleanup estimate loaded');}

  async function renderSafeChange(){const status=await api('/api/actions/status').catch(()=>null);$('#evidenceStage').innerHTML=question()+band(1,'Target & intent','<form class="s24-form" data-form="safe-action"><label class="s24-field"><span>Action</span><select name="action"><option value="rename">Rename</option><option value="vault">Vault</option><option value="reveal">Reveal in Finder</option></select></label><label class="s24-field"><span>Exact file path</span><input name="path" required placeholder="/Users/…/file"></label><label class="s24-field"><span>New name (rename only)</span><input name="new_name" placeholder="new-name.ext"></label><div class="s24-form-actions"><button class="s24-action primary" type="submit">Preview impact</button></div></form>','The server revalidates target scope and state before any reversible mutation.')+band(2,'Safety gate',`<div id="actionPreview">${empty('A fresh preview will show dependencies, consequences, exact confirmation phrase, and one-time code.')}</div>`)+(status?band(3,'Recovery state',ledger(primitiveRows(status,12))):'');activity('Ready',100,'Safe Actions ready');}

  async function previewSafeAction(form){const fd=new FormData(form),action=fd.get('action'),path=String(fd.get('path')||'').trim();if(action==='reveal'){await api('/api/actions/reveal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});notice('Reveal request sent to Finder.');return;}const req={action,path};if(action==='rename')req.new_name=String(fd.get('new_name')||'').trim();busy('Previewing impact',path);const p=await api('/api/actions/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)});state.actionPreview=p;const deps=p.dependencies||[],cons=p.consequences||[],signals=p.signals||[];$('#actionPreview').innerHTML=`${ledger([['Action',p.display_action||p.action],['Object',p.object_name],['Source',p.source],['Destination',p.destination||'—'],['Size',bytes(p.size)],['Risk',p.risk??0],['Reversible',p.reversible?'Yes':'No']])}${deps.length?`<div class="s24-note warn"><b>Dependencies</b><br>${deps.map(x=>esc(`${x.title}: ${x.detail}`)).join('<br>')}</div>`:''}${signals.length?`<div class="s24-note"><b>Review signals</b><br>${signals.map(esc).join('<br>')}</div>`:''}${cons.length?`<div class="s24-note warn"><b>Consequences</b><br>${cons.map(esc).join('<br>')}</div>`:''}<form class="s24-form" data-form="execute-action"><label class="s24-field"><span>Exact phrase</span><input name="phrase" required placeholder="${esc(p.confirm_phrase||'')}"></label><label class="s24-field"><span>One-time code</span><input name="code" required placeholder="${esc(p.confirm_code||'')}"></label><label class="s24-field"><span>Acknowledge</span><select name="ack"><option value="no">No</option><option value="yes">I reviewed the consequences</option></select></label><div class="s24-form-actions"><button class="s24-action danger" type="submit">Execute reversible change</button></div></form>`;activity('Preview ready',100,'No change executed yet');}

  async function executeSafeAction(form){if(!state.actionPreview)throw new Error('Create a fresh preview first.');const fd=new FormData(form);if(fd.get('ack')!=='yes')throw new Error('Review and acknowledge the consequences first.');busy('Revalidating & executing','Safe Action');const d=await api('/api/actions/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action_id:state.actionPreview.action_id,phrase:fd.get('phrase'),code:fd.get('code'),acknowledge:true})});state.actionPreview=null;jsonContext(`${d.action||'Action'} · ${d.status||'complete'}`,d,'The exact reversible operation and post-action observation returned by Sentinel.','A broader security verdict about the target.');notice(d.message||'Safe Action completed and recorded.');activity('Complete',100,'Recovery journal updated');}

  async function renderVisibility(){busy('Checking visibility','Coverage + capabilities');const [c,p,s]=await Promise.all([api('/api/coverage'),api('/api/capabilities'),api('/api/advanced-sensor/status').catch(()=>null)]);const items=c.items||[],caps=p.items||[];const coverage=items.length?`<div class="s24-feed">${items.map(x=>`<div class="s24-feed-item"><span>${esc(x.area||'area')}</span><div><h3>${esc(x.status||'unknown')}</h3><p>${esc(x.detail||'')}</p></div><div class="meta">${badge(x.status||'unknown',sev(x.status))}</div></div>`).join('')}</div>`:empty('No coverage metadata.');const capability=caps.length?table(['Source','Available','Purpose'],caps.map(x=>[esc(x.name),badge(x.available?'yes':'no',x.available?'good':'warn'),esc(x.purpose||'')])):empty('No capability metadata.');$('#evidenceStage').innerHTML=question()+band(1,'Coverage',coverage,`Available ${c.available||0} · limited ${c.limited||0} · unavailable ${c.unavailable||0}`)+band(2,'Evidence sources',capability,'Built-in macOS/Unix tools currently available to Sentinel.')+(s?band(3,'Advanced sensor',ledger(primitiveRows(s,12))):'');activity('Ready',100,'Visibility map loaded');}

  async function renderGuide(){$('#evidenceStage').innerHTML=question()+band(1,'Investigation model','<div class="s24-pipeline"><div class="s24-step done"><span>01</span><b>Observe</b></div><div class="s24-step done"><span>02</span><b>Connect</b></div><div class="s24-step active"><span>03</span><b>Compare</b></div><div class="s24-step"><span>04</span><b>Verify / Change</b></div></div>','Start with the smallest evidence path capable of answering the question.')+band(2,'What scores mean',ledger([['Attention','Where to look next','Not malware probability'],['Risk','Why an object was prioritized','Not proof of intent'],['Confidence','How strongly observations relate','Not maliciousness'],['Drift','Difference from an approved reference','Not automatic danger']]))+band(3,'Safety model','<div class="s24-note good">Sentinel is local-first, bounded, and evidence-oriented. File-changing actions are separate from observation and require a fresh server preview, explicit confirmation, revalidation, and recovery metadata.</div>');activity('Ready',100,'Model loaded');}

  registerLens('reclaim',renderReclaim);registerLens('change',renderSafeChange);registerLens('visibility',renderVisibility);registerLens('guide',renderGuide);
  S.previewSafeAction=previewSafeAction;S.executeSafeAction=executeSafeAction;S.renderSafeChange=renderSafeChange;
})();
