// SPDX-License-Identifier: MPL-2.0
(() => {
  'use strict';
  const S=window.SentinelApp;
  const {$,api,busy,activity,esc,fmt,sev,badge,question,band,empty,ledger,primitiveRows,registerLens}=S;

  async function renderChanges(){
    busy('Reading watch','Change Monitor');
    const d=await api('/api/changes/events'),s=d.status||{},events=d.events||[];
    const status=ledger([['Status',s.running?'Running':'Stopped'],['Mode',s.mode||'stopped'],['Events',s.event_count??events.length],['History',s.history_entries||0],['Needs rescan',s.needs_rescan?'YES':'No'],['Dropped signals',s.dropped_signals||0]]);
    const controls=`<form class="s24-form" data-form="change-watch"><label class="s24-field"><span>Watch scope</span><select name="preset"><option value="persistence">Persistence</option><option value="downloads">Downloads</option><option value="workspace">Workspace</option></select></label><label class="s24-field"><span>Fallback interval</span><select name="interval"><option value="1500">1.5 s</option><option value="2500" selected>2.5 s</option><option value="5000">5 s</option></select></label><div class="s24-form-actions"><button class="s24-action primary" type="submit">Start watch</button><button class="s24-action" type="button" data-do="stop-watch">Stop</button><button class="s24-action" type="button" data-do="review-watch">Reinspect</button></div></form>`;
    const feed=events.length?`<div class="s24-feed">${events.slice().reverse().map(e=>`<div class="s24-feed-item"><time>${esc(fmt(e.at))}</time><div><h3>${esc((e.path||'').split('/').pop()||e.kind||'Change')}</h3><p>${esc(e.why||e.kind||'')}</p><code>${esc(e.path||'')}</code></div><div class="meta">${badge(e.severity||'info',sev(e.severity))}${e.needs_rescan?badge('RESCAN','bad'):''}</div></div>`).join('')}</div>`:empty('No change events in this session.');
    $('#evidenceStage').innerHTML=question()+band(1,'Watch',controls)+band(2,'Continuity',status,'Dropped/root-changed conditions must create rescan-required state rather than false confidence.')+band(3,'Observed changes',feed);activity('Ready',100,'Change state loaded');
  }

  async function renderBehavior(){busy('Comparing','Behavior baseline');const [d,h]=await Promise.all([api('/api/behavior'),api('/api/behavior/health').catch(()=>null)]);const last=d.last_diff||{},changes=last.changes||[];const summary=ledger([['Baseline',d.has_baseline?'Available':'Not captured'],['Captured',d.baseline_at||'—'],['History',`${d.history_entries||0} / 40`],['Mode',d.persistence_mode||'persistent-local'],['Evidence index',last.risk_index??'—'],['Band',last.risk_band||'—']]);const feed=changes.length?`<div class="s24-feed">${changes.map(c=>`<div class="s24-feed-item"><span>${esc((c.kind||'change').replaceAll('_',' '))}</span><div><h3>${esc(c.title||'Change')}</h3><p>${esc((c.evidence||[]).join(' · '))}</p></div><div class="meta">${badge(c.severity||'info',sev(c.severity))}</div></div>`).join('')}</div>`:empty('No latest behavior difference is available.');$('#evidenceStage').innerHTML=question('<button class="s24-action primary" data-do="capture-behavior">Capture & compare</button>')+band(1,'Reference state',summary)+band(2,'Differences',feed,'Repeated behavior is not automatically learned as safe.')+(h?band(3,'Baseline health',ledger(primitiveRows(h,10))):'');activity('Ready',100,'Behavior state loaded');}

  async function renderReference(){busy('Reading reference','Trust profile');const [d,h]=await Promise.all([api('/api/trust/status'),api('/api/trust/health').catch(()=>null)]);const last=d.last_drift||{},changes=last.changes||[];const summary=ledger([['Profile',d.has_profile?'Available':'Not established'],['Updated',fmt(d.updated_at)],['Objects',d.objects||0],['Mode',d.persistence_mode||'persistent-local'],['Drift index',last.drift_index??'—'],['Coverage',last.profile_coverage!=null?`${last.profile_coverage}%`:'—']]);const feed=changes.length?`<div class="s24-feed">${changes.map(c=>`<div class="s24-feed-item"><span>${esc(c.kind||'drift')}</span><div><h3>${esc(c.title||'Reference difference')}</h3><p>${esc((c.evidence||[]).join(' · '))}</p>${c.object_key?`<code>${esc(c.object_key)}</code>`:''}</div><div class="meta">${badge(c.severity||'info',sev(c.severity))}${c.object_key?`<button class="s24-action" data-story-path="${esc(encodeURIComponent(c.object_key))}">Explain</button>`:''}</div></div>`).join('')}</div>`:empty('No current drift evidence is available.');$('#evidenceStage').innerHTML=question('<button class="s24-action" data-do="capture-reference">Establish reference</button><button class="s24-action primary" data-do="compare-reference">Compare now</button>')+band(1,'Approved reference',summary)+band(2,'Drift',feed,'Novelty or fingerprint change deserves context; it is not automatically malicious.')+(h?band(3,'Reference health',ledger(primitiveRows(h,10))):'');activity('Ready',100,'Reference state loaded');}

  registerLens('changes',renderChanges);registerLens('behavior',renderBehavior);registerLens('reference',renderReference);
  S.renderChanges=renderChanges;S.renderBehavior=renderBehavior;S.renderReference=renderReference;
})();
