// SPDX-License-Identifier: MPL-2.0
(() => {
  'use strict';
  const S=window.SentinelApp;
  const {$,$$,state,api,busy,activity,notice,esc,bytes,fmt,badge,question,band,empty,ledger,table,primitiveRows,registerLens}=S;

  async function renderMachine(){busy('Reading machine','System Profile');const d=await api('/api/system-profile');const rows=[['Model',d.model_name,d.model_identifier],['Chip',d.chip||d.processor,d.platform_family],['Architecture',d.architecture,d.engine_explanation],['Physical cores',d.physical_cores],['Logical cores',d.logical_cores],['Memory',bytes(d.memory_bytes)],['macOS',d.os_version,d.os_build],['Kernel',d.kernel_version],['Rosetta',d.rosetta_translated?'Yes':'No'],['Root storage',bytes(d.disk_total),`${bytes(d.disk_available)} available`]];$('#evidenceStage').innerHTML=question()+band(1,'Machine identity',ledger(rows),'Unique serial number and Hardware UUID are intentionally unnecessary for this view.')+band(2,'Runtime implication',`<div class="s24-note good">${esc(d.engine_explanation||'Sentinel uses the architecture-matched local engine packaged in the Universal app.')}</div>`);activity('Ready',100,'Machine profile loaded');}

  async function renderProcesses(){busy('Reading processes','Current process snapshot');const d=await api('/api/processes');state.processRows=d.processes||[];const rows=state.processRows.slice(0,260).map(p=>[`<b>${esc(p.pid)}</b>`,`${Number(p.cpu||0).toFixed(1)}%`,`${Number(p.memory||0).toFixed(1)}%`,esc(p.user||''),`<code>${esc(p.command||'')}</code>`,`<button data-story-pid="${Number(p.pid)}">Explain</button>`]);$('#evidenceStage').innerHTML=question()+band(1,'Running software',rows.length?table(['PID','CPU','Memory','User','Command',''],rows):empty('No process rows returned.'),'Current state only; historical process activity requires prior capture.');activity('Ready',100,`${state.processRows.length} processes returned`);}

  async function renderStartup(){busy('Reading startup','Launch configuration');const d=await api('/api/startup');const items=d.items||[];const rows=items.slice(0,260).map(x=>[badge(x.risk??0,Number(x.risk||0)>=70?'bad':Number(x.risk||0)>=35?'warn':''),esc(x.scope||''),esc(x.manifest?.label||x.name||''),`<code>${esc(x.executable||x.target||'')}</code>`,`<code>${esc(x.path||x.manifest_path||'')}</code>`]);$('#evidenceStage').innerHTML=question()+band(1,'Launch declarations',items.length?table(['Risk','Scope','Item','Executable','Manifest'],rows):empty('No visible startup items returned.'),'Launch persistence is common; path, identity and behavior determine whether it deserves review.');activity('Ready',100,`${items.length} startup items`);}

  async function renderGenericLens(endpoint,title,description,method='GET'){
    busy('Reading evidence',title);const d=await api(endpoint,{method});const rows=primitiveRows(d,18);const arrays=Object.entries(d||{}).filter(([,v])=>Array.isArray(v)).sort((a,b)=>b[1].length-a[1].length);let body=ledger(rows);if(arrays.length){const [name,list]=arrays[0];if(list.length&&typeof list[0]==='object'){const keys=[...new Set(list.slice(0,8).flatMap(x=>Object.keys(x).filter(k=>['string','number','boolean'].includes(typeof x[k]))))].slice(0,6);body+=`<div style="height:16px"></div>`+table(keys.map(k=>k.replaceAll('_',' ')),list.slice(0,200).map(x=>keys.map(k=>`<span class="${k.includes('path')?'mono':''}">${esc(x[k]??'')}</span>`)));}else if(list.length)body+=`<div class="s24-note">${esc(name)}: ${esc(list.slice(0,20).join(' · '))}</div>`;}$('#evidenceStage').innerHTML=question()+band(1,title,body,description);activity('Ready',100,title+' loaded');
  }

  async function renderStorage(){$('#evidenceStage').innerHTML=question()+band(1,'Acquisition',`<form class="s24-form" data-form="storage"><label class="s24-field"><span>Scope</span><select name="scope"><option value="home">Home</option><option value="downloads">Downloads</option><option value="workspace">Workspace</option></select></label><label class="s24-field"><span>Minimum file MB</span><input name="min" type="number" min="1" max="10240" value="100"></label><label class="s24-field"><span>Large-file limit</span><input name="limit" type="number" min="10" max="2000" value="200"></label><div class="s24-form-actions"><button class="s24-action primary" type="submit">Measure storage</button><button class="s24-action" type="button" data-do="cancel-storage">Cancel</button></div></form><div id="storagePipeline" class="s24-pipeline"><div class="s24-step"><span>01</span><b>Traverse</b></div><div class="s24-step"><span>02</span><b>Measure</b></div><div class="s24-step"><span>03</span><b>Hash candidates</b></div><div class="s24-step"><span>04</span><b>Report</b></div></div>`,'Scanning is bounded and cancellable. Progress appears only after a real localhost request starts.')+band(2,'Measured footprint',`<div id="storageSummary">${empty('Run a measurement to populate observed numbers.')}</div>`)+band(3,'Objects',`<div id="storageObjects">${empty('No storage result yet.')}</div>`);activity('Ready',0,'Storage measurement idle');}

  async function startStorage(form){if(state.scanTimer)clearTimeout(state.scanTimer);const fd=new FormData(form);busy('Starting scan','Bounded localhost request');const job=await api('/api/storage/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:fd.get('scope'),min_mb:Number(fd.get('min')),limit:Number(fd.get('limit'))})});state.scanJob=job.id;pollStorage();}

  async function pollStorage(){if(!state.scanJob)return;try{const j=await api('/api/storage/jobs?id='+encodeURIComponent(state.scanJob));const phase=String(j.phase||'scan'),phasePct=Number(j.phase_percent||0);let detail=`${Number(j.files_visited||0).toLocaleString()} files · ${Number(j.dirs_visited||0).toLocaleString()} folders`;if(j.slow_paths_skipped)detail+=` · ${Number(j.slow_paths_skipped).toLocaleString()} slow paths skipped`;if(j.hash_files_total)detail+=` · hashes ${Number(j.hash_files_done||0)}/${Number(j.hash_files_total||0)}`;if(j.hash_bytes_total)detail+=` · ${bytes(j.hash_bytes_done||0)} / ${bytes(j.hash_bytes_total||0)}`;if(j.current_hash_path)detail+=` · ${j.current_hash_path}`;activity(phase.replaceAll('_',' '),phasePct,detail);const steps=$$('#storagePipeline .s24-step'),idx=phase.includes('hash')?2:phase.includes('report')?3:phase.includes('measure')?1:0;steps.forEach((x,i)=>{x.classList.toggle('active',i===idx);x.classList.toggle('done',i<idx);});if(j.status==='running'){state.scanTimer=setTimeout(pollStorage,500);return;}if(j.status==='failed')throw new Error(j.error||'Storage scan failed');if(j.result)renderStorageResult(j.result,j.status);activity(j.status==='cancelled'?'Cancelled':'Complete',100,j.status==='cancelled'?'Partial measured result preserved when available.':'Building storage report complete.');}catch(e){notice(e.message);activity('Error',0,e.message);}}

  function renderStorageResult(d,status){const summary=$('#storageSummary'),objects=$('#storageObjects');if(!summary||!objects)return;summary.innerHTML=ledger([['Status',status||'complete'],['Files visited',Number(d.files_visited||0).toLocaleString()],['Folders visited',Number(d.dirs_visited||0).toLocaleString()],['Visible bytes',bytes(d.visible_bytes)],['Permission limits',d.permission_errors||0],['Slow paths skipped',d.slow_paths_skipped||0],['Duplicate hash bytes',bytes(d.duplicate_hash_bytes||0)]]);const files=d.large_files||[],dups=d.duplicates||[],families=d.families||[];let body=files.length?table(['Size','Modified','File','Path',''],files.slice(0,300).map(f=>[`<b>${bytes(f.size)}</b>`,esc(fmt(f.modified_unix)),esc(f.name),`<code>${esc(f.path)}</code>`,`<button data-story-path="${esc(encodeURIComponent(f.path))}">Explain</button>`])):empty('No large files matched the scan threshold.');if(dups.length)body+=`<div class="s24-note good">${dups.length} exact duplicate group(s) use hash agreement. Filename families remain separate heuristics.</div>`;if(families.length)body+=`<div class="s24-note warn">${families.length} possible version family/families are naming heuristics only.</div>`;objects.innerHTML=body;}

  registerLens('machine',renderMachine);registerLens('processes',renderProcesses);registerLens('startup',renderStartup);registerLens('persistence',()=>renderGenericLens('/api/persistence','Persistence comparison','Visible LaunchAgent/LaunchDaemon configuration state and bounded comparison.'));registerLens('background',()=>renderGenericLens('/api/background','Background registrations','Background Task Management registrations macOS exposes to this process.'));registerLens('network',()=>renderGenericLens('/api/network','Current TCP evidence','Current network snapshot only; encrypted content and unobserved history are outside this evidence.'));registerLens('storage',renderStorage);
  S.startStorage=startStorage;S.pollStorage=pollStorage;S.renderStorage=renderStorage;
})();
