// SPDX-License-Identifier: MPL-2.0
(() => {
  // Desktop App View is a first-principles workbench layered over the same
  // trusted feature IDs and app.js event handlers. We move existing nodes
  // instead of cloning or replacing them, so every backend capability remains wired.
  if (window.__sentinelDesktopUIInstalled) return;
  window.__sentinelDesktopUIInstalled = true;

  const css = document.createElement('link');
  css.rel = 'stylesheet';
  css.href = '/desktop-ui.css';
  css.id = 'sentinel-desktop-ui-css';
  document.head.appendChild(css);

  document.body.classList.remove('easy-mode');
  const legacyGroup = document.querySelector('.nav-group-label.advanced-nav');
  if (legacyGroup) { legacyGroup.textContent = 'More tools'; legacyGroup.hidden = true; }

  const IA = {
    overview:{group:'NOW',nav:'Command',title:'Command',sub:'Current state, evidence quality, and the shortest useful next step.',stage:'Orient',question:'What deserves attention now?'},
    quickcheck:{group:'NOW',nav:'Snapshot',title:'Snapshot',sub:'One bounded read-only observation, converted into a review queue.',stage:'Observe',question:'What is worth inspecting next?'},
    incidents:{group:'INVESTIGATE',nav:'Cases',title:'Cases',sub:'Correlated observations assembled into investigation stories.',stage:'Correlate',question:'Which observations belong to the same story?'},
    weakness:{group:'INVESTIGATE',nav:'Investigate',title:'Investigate',sub:'Start with a concrete target, search the evidence, then check visibility limits.',stage:'Query',question:'What exactly am I trying to understand?'},
    intelligence:{group:'INVESTIGATE',nav:'Evidence',title:'Evidence',sub:'Relationships, time, and object context in one investigation surface.',stage:'Connect',question:'How are these objects related, and in what order?'},
    behavior:{group:'INVESTIGATE',nav:'Behavior',title:'Behavior',sub:'Compare bounded captures to separate stable state from meaningful change.',stage:'Compare',question:'What changed since the previous observation?'},
    trust:{group:'INVESTIGATE',nav:'Reference',title:'Reference',sub:'Compare the current state with a reference you explicitly approved.',stage:'Compare',question:'What differs from my approved reference?'},
    hardware:{group:'SYSTEM',nav:'Machine',title:'Machine',sub:'Hardware and runtime context for this investigation.',stage:'Context',question:'What machine and runtime am I observing?'},
    processes:{group:'SYSTEM',nav:'Processes',title:'Processes',sub:'Running software connected to executable, signature, and network context.',stage:'Inspect',question:'What is running, and what is it connected to?'},
    startup:{group:'SYSTEM',nav:'Startup',title:'Startup',sub:'Declarations that cause software to launch automatically.',stage:'Inspect',question:'What is configured to start automatically?'},
    persistence:{group:'SYSTEM',nav:'Persistence',title:'Persistence',sub:'Visible launch configuration compared with a session baseline.',stage:'Compare',question:'Did startup configuration change?'},
    background:{group:'SYSTEM',nav:'Background',title:'Background',sub:'Modern macOS background registrations beyond classic launch items.',stage:'Inspect',question:'What background registrations exist?'},
    network:{group:'SYSTEM',nav:'Network',title:'Network',sub:'A bounded TCP snapshot connected back to local processes.',stage:'Inspect',question:'Which processes currently have TCP activity?'},
    storage:{group:'SYSTEM',nav:'Storage',title:'Storage',sub:'Measured space use, exact duplicates, and clearly labeled heuristics.',stage:'Measure',question:'Where is storage pressure coming from?'},
    security:{group:'VERIFY & RESOLVE',nav:'Audit',title:'Audit',sub:'Explainable review signals without converting a score into a verdict.',stage:'Assess',question:'Which evidence deserves review, and why?'},
    integrity:{group:'VERIFY & RESOLVE',nav:'Verify File',title:'Verify File',sub:'One local object inspected with hashes and macOS trust context.',stage:'Verify',question:'What can I establish about this exact object?'},
    actions:{group:'VERIFY & RESOLVE',nav:'Resolve',title:'Resolve',sub:'A reversible change only after evidence and impact review.',stage:'Resolve',question:'What is the safest reversible change?'},
    cleanup:{group:'VERIFY & RESOLVE',nav:'Reclaim',title:'Reclaim',sub:'Reviewable storage candidates with no automatic deletion.',stage:'Review',question:'What space is worth reviewing?'},
    guide:{group:'SUPPORT',nav:'Help & Access',title:'Help & Access',sub:'Visibility boundaries, evidence semantics, and safe operating paths.',stage:'Understand',question:'What can Sentinel see, and what do the results mean?'}
  };

  const READING = {
    overview:['Read current state and readiness.','Use it to choose the narrowest next investigation.','Do not treat an unreviewed status as proof of safety.'],
    quickcheck:['Read attention state, then the review queue.','Use it to prioritize where to look next.','Attention Index is not malware probability.'],
    incidents:['Read the timeline and connected evidence together.','Use confidence to judge relationship strength.','Confidence is not maliciousness.'],
    weakness:['Start with one target or question.','Use coverage to judge how complete the answer can be.','Missing visibility is not evidence that nothing exists.'],
    intelligence:['Read graph, timeline, then object narrative.','Use multiple evidence layers before forming a conclusion.','One edge or endpoint is never a verdict.'],
    behavior:['Read what changed and how the trend moved.','Use repeated captures to separate stable from new state.','Change pressure is not danger.'],
    trust:['Read drift from the approved reference.','Use reference matches as context.','Reference membership is not a security certificate.'],
    hardware:['Read architecture and runtime before interpreting capability.','Use it to explain compatibility and visibility.','Hardware identity does not imply security state.'],
    processes:['Read executable identity before network context.','Use process detail to connect path, signature, and endpoints.','High CPU or a public connection alone is not suspicious.'],
    startup:['Read declaration, path, and manifest behavior together.','Use it to understand automatic launch behavior.','Persistence is common in legitimate software.'],
    persistence:['Compare current launch configuration with the session baseline.','Use additions, removals, and content changes as review signals.','A changed plist is not automatically malicious.'],
    background:['Read registration identity and source together.','Use it to complement classic startup evidence.','A background registration alone is not suspicious.'],
    network:['Connect endpoints back to local processes.','Use network state as context for an object story.','A public endpoint is common and not suspicious by itself.'],
    storage:['Measure first; compare candidates second.','Exact duplicates require hash agreement; version families are heuristic.','Large, old, or duplicated-looking does not mean disposable.'],
    security:['Read the reasons behind the score.','Use severity to prioritize review.','The score is not malware probability.'],
    integrity:['Read hash, signature, and Gatekeeper context together.','Use the result to establish identity and platform trust context.','Signed or accepted does not guarantee good intent.'],
    actions:['Review evidence and dependency impact before confirmation.','Use only reversible actions when the expected benefit is clear.','Resolve does not prove the target is malware.'],
    cleanup:['Measure reviewable space before selecting objects.','Use Resolve for eligible files after review.','Sentinel does not automatically delete candidates.'],
    guide:['Read the visibility boundary before relying on a result.','Use the shortest workflow that answers the question.','Sentinel must degrade confidence rather than invent missing evidence.']
  };

  const GROUPS=[['NOW',['overview','quickcheck']],['INVESTIGATE',['incidents','weakness','intelligence','behavior','trust']],['SYSTEM',['hardware','processes','startup','persistence','background','network','storage']],['VERIFY & RESOLVE',['security','integrity','actions','cleanup']],['SUPPORT',['guide']]];
  const q=(root,selector)=>(root||document).querySelector(selector);
  const qa=(root,selector)=>[...(root||document).querySelectorAll(selector)];
  const make=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;};
  const setText=(selector,text,root=document)=>{const n=q(root,selector);if(n&&typeof text==='string')n.textContent=text;return n;};

  function relabelButtons(){
    const labels={exportReport:'Export evidence report',pageHelpToggle:'Explain view',refresh:'Refresh view',runReadiness:'Verify Sentinel',exportDiagnostics:'Export diagnostics',loadCapabilities:'Refresh sources',loadSelfIntegrity:'Verify Sentinel binary',runQuickCheck:'Take snapshot',guidedSnapshot:'Capture full evidence',loadReviewQueue:'Refresh queue',loadSystemProfile:'Read machine',rebuildIncidents:'Rebuild cases',loadIncidentHistory:'Case history',closeIncidentDeepReview:'Close review',startChanges:'Start watch',stopChanges:'Stop watch',reviewChanges:'Review changed objects',reconcileChanges:'Reconcile',clearChanges:'Clear inbox',loadChangeHistory:'Watch history',refreshChanges:'Refresh inbox',startScan:'Measure storage',cancelScan:'Cancel',runAudit:'Run evidence audit',inspectIntegrity:'Verify object',captureEvidence:'Capture evidence',loadEvidence:'Refresh relationships',loadTimeline:'Refresh timeline',captureBehavior:'Capture & compare',loadBehavior:'Load comparison',loadBehaviorHistory:'Refresh trend',loadBehaviorHealth:'Verify history',compareTrust:'Compare to reference',captureTrust:'Set reference',loadTrustHealth:'Verify reference',exportTrust:'Export reference',restoreTrust:'Restore previous',loadTrustHistory:'Refresh comparisons',loadProcesses:'Refresh processes',closeProcessDetail:'Close detail',loadStartup:'Refresh startup',capturePersistence:'Capture / compare',loadPersistence:'Refresh state',loadBackground:'Refresh background',loadNetwork:'Refresh network',previewCleanup:'Analyze reclaimable space',loadActionHealth:'Verify recovery',previewAction:'Preview reversible action',revealActionPath:'Reveal target',executeAction:'Confirm reversible action',loadVault:'Refresh Vault',loadActionJournal:'Refresh journal',runDeepSearch:'Search filenames',runWeaknessAudit:'Audit visibility',loadCoverage:'Refresh coverage',loadAdvancedSensor:'Check sensor boundary'};
    for(const [id,label] of Object.entries(labels))setText(`#${id}`,label);
    qa(document,'[data-go="quickcheck"]').forEach(n=>n.textContent='Take snapshot');
    qa(document,'[data-go="storage"]').forEach(n=>n.textContent='Measure storage');
    qa(document,'[data-go="weakness"]').forEach(n=>n.textContent='Investigate evidence');
    qa(document,'[data-go="changes"]').forEach(n=>n.textContent='Watch changes');
    qa(document,'[data-go="processes"]').forEach(n=>n.textContent='Inspect processes');
    qa(document,'[data-go="security"]').forEach(n=>n.textContent='Run audit');
    qa(document,'[data-go="behavior"]').forEach(n=>n.textContent='Compare behavior');
    qa(document,'[data-go="trust"]').forEach(n=>n.textContent='Open reference');
  }

  function installNavigation(){
    const nav=q(document,'.sidebar nav'); if(!nav||nav.dataset.desktopRebuilt==='1')return; nav.dataset.desktopRebuilt='1';
    const old=q(nav,'.nav-group-label');if(old)old.hidden=true;
    for(const [groupName,views] of GROUPS){const group=make('section','desktop-nav-group');group.appendChild(make('div','desktop-nav-label',groupName));for(const view of views){const button=q(nav,`.nav[data-view="${view}"]`);if(!button)continue;button.textContent=IA[view].nav;button.dataset.desktopGroup=groupName;group.appendChild(button);}nav.appendChild(group);}
  }

  function rewriteStaticCopy(){
    setText('.brand small','Local evidence workbench');setText('.privacy b','Local session');setText('.privacy small','Loopback only · reversible changes');
    const h2Copy={overview:['Start with the next decision','Sentinel readiness','Machine context','Operating boundaries','Evidence sources','Sentinel binary identity'],quickcheck:['Decision snapshot','Recommended paths','Review queue'],hardware:['Machine identity','Hardware','Runtime','Field notes','Privacy boundary'],incidents:['Build cases','Case queue','Deep review','Confidence model','Investigation path'],changes:['Watch control','Monitoring model','Targeted review','Change inbox'],storage:['Measure storage','Largest areas','File-type footprint','Exact duplicates','Version families','Largest objects'],security:['Audit summary'],integrity:['Verify one object'],intelligence:['Capture evidence','Relationship graph','Timeline','Object narrative'],behavior:['Behavior comparison','Evidence trend','Baseline health','Observed changes','Persistence boundary'],trust:['Reference comparison','Reference health','Reference controls','Comparison history','Drift evidence'],processes:['Running processes','Process detail'],startup:['Startup declarations'],persistence:['Persistence comparison'],background:['Background registrations','Interpretation'],network:['TCP snapshot'],cleanup:['Reclaim preview'],actions:['Resolve safely','Recovery health','Action semantics','Prepare action','Confirmation gate','Vault','Recovery journal'],weakness:['Evidence query','Visibility audit','Coverage map','Sensor boundary'],guide:['Operating path','Permissions','Interpretation','Design basis','Glossary']};
    for(const [view,titles] of Object.entries(h2Copy)){const section=document.getElementById(view);if(!section)continue;qa(section,'h2').forEach((node,index)=>{if(titles[index])node.textContent=titles[index];});}
    const descriptions={overview:'Read state and readiness, then choose the smallest investigation that can answer the question.',quickcheck:'Combine current local evidence into one read-only attention state. No baseline or file state changes.',hardware:'Read model, processor, architecture, memory, operating system, and runtime without collecting unique hardware identifiers.',incidents:'Group related observations so timing, identity, persistence, and reference drift can be reviewed together.',changes:'Choose a narrow scope, observe changes, then re-inspect only what moved.',storage:'Measure first. Exact duplicates are hash-backed; version families remain heuristics.',security:'Correlate location, persistence, signing, and current network evidence. Read the reasons, not just the score.',integrity:'Verify one exact path with a content fingerprint and macOS trust context.',intelligence:'Capture a bounded relationship snapshot and read graph, time, and object context together.',behavior:'Compare current bounded metadata with the previous capture. The result measures change, not danger.',trust:'Compare current state with a reference you explicitly approved. A match is context, not certification.',processes:'Start with what is running now, then connect executable identity, signature context, and TCP activity.',startup:'Read launch declarations together with executable path and manifest meaning.',persistence:'Compare visible launch configuration for additions, removals, and same-name content changes.',background:'Read modern macOS background registrations when the system exposes them.',network:'Read current TCP activity as process context, not as a verdict.',cleanup:'Estimate reviewable space without deleting anything. Send only reviewed eligible files to Resolve.',actions:'Resolve is the last step: evidence, impact preview, explicit confirmation, then a reversible change.',weakness:'Start from one concrete query. Search current evidence first; use bounded filename discovery only when needed.',guide:'Observe, investigate, verify, then resolve only when the evidence supports action.'};
    for(const [view,text] of Object.entries(descriptions)){const section=document.getElementById(view);if(!section)continue;const p=q(section,'.section-head > div > p')||q(section,'article.card p');if(p)p.textContent=text;}
    setText('.welcome-card > div > p',descriptions.overview,document.getElementById('overview'));setText('.action-warning > p',descriptions.actions,document.getElementById('actions'));
    setText('.welcome-card .eyebrow','LOCAL EVIDENCE WORKBENCH',document.getElementById('overview'));setText('.quick-hero .eyebrow','READ-ONLY OBSERVATION',document.getElementById('quickcheck'));setText('.hardware-hero .eyebrow','LOCAL MACHINE CONTEXT',document.getElementById('hardware'));setText('#incidents .eyebrow','CORRELATED EVIDENCE');setText('.change-hero .eyebrow','BOUNDED CHANGE WATCH',document.getElementById('changes'));
    const search=document.getElementById('globalSearch');if(search)search.placeholder='Search evidence… process, path, endpoint, severity';const deep=document.getElementById('deepSearchQ');if(deep)deep.placeholder='Filename or path fragment';const fileFilter=document.getElementById('fileFilter');if(fileFilter)fileFilter.placeholder='Filter measured objects';const processFilter=document.getElementById('processFilter');if(processFilter)processFilter.placeholder='Filter running processes';
  }

  function rewriteEmptyStates(){
    const states={readinessBody:'Not checked yet. Verify Sentinel before relying on long monitoring or Resolve.',selfIntegrityBody:'Binary identity has not been verified in this session.',quickCheckStatus:'No snapshot yet. Take one bounded read-only observation to establish what deserves review.',quickRecommendations:'Take a snapshot first; recommended paths will appear here.',reviewQueue:'No review queue loaded. Refresh after a snapshot or whenever you want one prioritized list.',hardwareSummary:'Machine context has not been read yet.',incidentSummary:'No case model yet. Build cases after evidence capture or observed changes.',incidentList:'No cases loaded.',incidentDeepReviewBody:'Select a case and run Deep Review.',changeStatus:'Watch is idle. Choose a narrow scope before starting.',changeReview:'No targeted review yet.',changeEvents:'No observed change events in the current view.',deepSearchResults:'Use bounded filename search only when current evidence cannot locate the object.',weaknessAudit:'Visibility has not been audited yet.',coverageMap:'Coverage has not been read yet.',advancedSensorStatus:'Sensor boundary has not been checked yet.',integrityBody:'Enter one exact path to verify locally.',graphWrap:'No relationship snapshot yet. Capture evidence to build the graph.',timelineList:'No timeline loaded yet.',storyBody:'Select an object from the graph, a process, or a measured file.',behaviorBaseline:'No behavior comparison loaded yet.',behaviorTrend:'No trend loaded yet.',baselineHealth:'History integrity has not been verified yet.',behaviorChanges:'No observed behavior comparison yet.',trustStatus:'No approved reference status loaded yet.',trustHealth:'Reference integrity has not been verified yet.',trustHistoryList:'No reference comparisons loaded yet.',trustChanges:'No drift evidence loaded yet.',processTable:'Process snapshot has not been loaded yet.',startupTable:'Startup declarations have not been loaded yet.',persistenceChanges:'Capture once to establish the session comparison point.',backgroundTable:'Background registrations have not been loaded yet.',networkTable:'TCP snapshot has not been loaded yet.',cleanupList:'No reclaim analysis yet.',actionStatus:'Recovery state has not been verified yet.',vaultList:'Vault state has not been loaded yet.',actionJournal:'Recovery journal has not been loaded yet.',filesTable:'No storage measurement yet.'};
    for(const [id,text] of Object.entries(states)){const host=document.getElementById(id);const empty=host&&q(host,'.empty');if(empty)empty.textContent=text;}
  }

  function addWorkspaceIntro(section,meta){
    if(!section||q(section,':scope > .workspace-intro'))return;
    const intro=make('div','workspace-intro');
    const top=make('div','workspace-intro-main');top.append(make('span','workspace-stage',meta.stage),make('h2','workspace-question',meta.question),make('p','workspace-intent',meta.sub));intro.appendChild(top);
    const rules=READING[section.id]||[];if(rules.length){const rail=make('div','evidence-reading-contract');[['READ',rules[0]],['USE',rules[1]],['DO NOT INFER',rules[2]]].forEach(([label,text])=>{const item=make('div','evidence-reading-item');item.append(make('span','',label),make('p','',text));rail.appendChild(item);});intro.appendChild(rail);}
    section.prepend(intro);
  }
  function zone(className,label){const outer=make('div',`workspace-zone ${className}`);if(label)outer.appendChild(make('div','workspace-zone-label',label));const body=make('div','workspace-zone-body');outer.appendChild(body);outer.body=body;return outer;}

  function composeOverview(){const section=document.getElementById('overview');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const welcome=q(section,'.welcome-card'),ready=q(section,'.readiness-card'),metrics=q(section,'.hero-grid'),context=q(section,'.two-col'),cards=qa(section,':scope > article.card').filter(n=>n!==welcome&&n!==ready),evidenceSources=cards[0],selfIntegrity=cards[1],layout=make('div','command-workbench'),main=zone('command-primary','DECIDE'),side=zone('command-side','READINESS'),wide=zone('command-wide','EVIDENCE BOUNDARY');if(welcome)main.body.appendChild(welcome);if(metrics)main.body.appendChild(metrics);if(context)main.body.appendChild(context);if(ready)side.body.appendChild(ready);if(selfIntegrity)side.body.appendChild(selfIntegrity);if(evidenceSources)wide.body.appendChild(evidenceSources);layout.append(main,side,wide);section.appendChild(layout);}
  function composeTwoLane(view,mainSelectors,sideSelectors,wideSelectors=[]){const section=document.getElementById(view);if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const layout=make('div','two-lane-workbench'),main=zone('lane-main','PRIMARY'),side=zone('lane-side','CONTEXT'),wide=zone('lane-wide','DETAIL'),claim=(selector,target)=>qa(section,`:scope > ${selector}`).forEach(node=>target.body.appendChild(node));mainSelectors.forEach(s=>claim(s,main));sideSelectors.forEach(s=>claim(s,side));wideSelectors.forEach(s=>claim(s,wide));[...section.children].filter(node=>!node.classList.contains('workspace-intro')&&!node.classList.contains('two-lane-workbench')&&!node.classList.contains('workspace-zone')).forEach(node=>wide.body.appendChild(node));layout.append(main,side);if(wide.body.children.length)layout.appendChild(wide);section.appendChild(layout);}
  function composeQuickCheck(){const section=document.getElementById('quickcheck');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const hero=q(section,'.quick-hero'),metrics=document.getElementById('quickCheckMetrics'),cards=qa(section,':scope > article.card').filter(n=>n!==hero),recommended=cards[0],queue=cards[1],layout=make('div','decision-workbench'),observe=zone('decision-observe','OBSERVE'),review=zone('decision-review','REVIEW'),next=zone('decision-next','NEXT');if(hero)observe.body.appendChild(hero);if(metrics)observe.body.appendChild(metrics);if(queue)review.body.appendChild(queue);if(recommended)next.body.appendChild(recommended);layout.append(observe,review,next);section.appendChild(layout);}
  function composeIncidents(){const section=document.getElementById('incidents');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const articles=qa(section,':scope > article.card'),summary=articles[0],list=articles[1],deep=document.getElementById('incidentDeepReviewCard'),guide=q(section,':scope > .two-col'),layout=make('div','case-workbench'),queueZone=zone('case-queue','CASES'),detailZone=zone('case-detail','SELECTED CASE'),modelZone=zone('case-model','READING MODEL');if(summary)queueZone.body.appendChild(summary);if(list)queueZone.body.appendChild(list);if(deep)detailZone.body.appendChild(deep);if(guide)modelZone.body.appendChild(guide);layout.append(queueZone,detailZone,modelZone);section.appendChild(layout);}
  function composeChanges(){const section=document.getElementById('changes');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const hero=q(section,'.change-hero'),pair=q(section,':scope > .two-col'),inbox=qa(section,':scope > article.card').find(n=>n!==hero),layout=make('div','watch-workbench'),control=zone('watch-control','WATCH'),events=zone('watch-events','INBOX'),review=zone('watch-review','REINSPECT'),model=zone('watch-model','CONFIDENCE');if(hero)control.body.appendChild(hero);if(inbox)events.body.appendChild(inbox);if(pair){const parts=[...pair.children];if(parts[1])review.body.appendChild(parts[1]);if(parts[0])model.body.appendChild(parts[0]);pair.remove();}layout.append(control,events,review,model);section.appendChild(layout);}
  function composeWeakness(){const section=document.getElementById('weakness');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const queryCard=q(section,'.power-search-card'),pair=q(section,':scope > .two-col'),sensor=qa(section,':scope > article.card').find(n=>n!==queryCard),layout=make('div','investigate-workbench'),queryZone=zone('investigate-query','QUERY'),visibility=zone('investigate-visibility','VISIBILITY'),boundary=zone('investigate-boundary','SENSOR BOUNDARY');if(queryCard)queryZone.body.appendChild(queryCard);if(pair){[...pair.children].forEach(n=>visibility.body.appendChild(n));pair.remove();}if(sensor)boundary.body.appendChild(sensor);layout.append(queryZone,visibility,boundary);section.appendChild(layout);}
  function composeStorage(){const section=document.getElementById('storage');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const scan=q(section,':scope > article.card'),insights=document.getElementById('storageInsights'),duplicates=document.getElementById('duplicatesPanel'),families=document.getElementById('familiesPanel'),files=qa(section,':scope > article.card').find(n=>n!==scan),layout=make('div','storage-workbench'),control=zone('storage-control','MEASURE'),footprint=zone('storage-footprint','FOOTPRINT'),objects=zone('storage-objects','OBJECTS'),candidates=zone('storage-candidates','COMPARE');if(scan)control.body.appendChild(scan);if(insights)footprint.body.appendChild(insights);if(files)objects.body.appendChild(files);if(duplicates)candidates.body.appendChild(duplicates);if(families)candidates.body.appendChild(families);layout.append(control,footprint,objects,candidates);section.appendChild(layout);}
  function composeEvidence(){const section=document.getElementById('intelligence');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const hero=q(section,'.intelligence-hero'),graph=qa(section,':scope > article.card').find(n=>n!==hero),bottom=q(section,'.intelligence-bottom'),layout=make('div','evidence-workbench'),capture=zone('evidence-capture','CAPTURE'),graphZone=zone('evidence-graph-zone','RELATIONSHIPS'),time=zone('evidence-time','TIME'),object=zone('evidence-object','OBJECT');if(hero)capture.body.appendChild(hero);if(graph)graphZone.body.appendChild(graph);if(bottom){const parts=[...bottom.children];if(parts[0])time.body.appendChild(parts[0]);if(parts[1])object.body.appendChild(parts[1]);bottom.remove();}layout.append(capture,graphZone,time,object);section.appendChild(layout);}
  function composeActions(){const section=document.getElementById('actions');if(!section||section.dataset.desktopComposed)return;section.dataset.desktopComposed='1';const warning=q(section,'.action-warning'),pair=q(section,':scope > .two-col'),formCard=qa(section,':scope > article.card').find(n=>q(n,'#actionForm')),preview=document.getElementById('actionPreviewCard'),vault=qa(section,':scope > article.card').find(n=>q(n,'#vaultList')),journal=qa(section,':scope > article.card').find(n=>q(n,'#actionJournal')),layout=make('div','resolve-workbench'),guard=zone('resolve-guard','SAFETY GATE'),act=zone('resolve-action','TARGET & IMPACT'),recover=zone('resolve-recover','RECOVERY');if(warning)guard.body.appendChild(warning);if(pair){[...pair.children].forEach(n=>guard.body.appendChild(n));pair.remove();}if(formCard)act.body.appendChild(formCard);if(preview)act.body.appendChild(preview);if(vault)recover.body.appendChild(vault);if(journal)recover.body.appendChild(journal);layout.append(guard,act,recover);section.appendChild(layout);}
  function composeGenericViews(){composeTwoLane('hardware',['.hardware-hero','.two-col'],['.privacy-hardware'],['article.card:not(.hardware-hero):not(.privacy-hardware)']);composeTwoLane('security',['article.card'],['#findings']);composeTwoLane('integrity',['article.card'],[]);composeTwoLane('behavior',['.behavior-hero'],['.behavior-history-grid'],['article.card']);composeTwoLane('trust',['.trust-hero','article.card:last-of-type'],['.two-col'],['article.card']);composeTwoLane('processes',['article.card:first-of-type'],['#processDetail']);composeTwoLane('startup',['article.card'],[]);composeTwoLane('persistence',['article.card'],[]);composeTwoLane('background',['article.card:first-of-type'],['article.card:last-of-type']);composeTwoLane('network',['article.card'],[]);composeTwoLane('cleanup',['article.card'],[]);composeTwoLane('guide',['article.card:first-of-type'],['.two-col'],['article.card']);}
  function composeAllViews(){for(const [view,meta] of Object.entries(IA))addWorkspaceIntro(document.getElementById(view),meta);composeOverview();composeQuickCheck();composeIncidents();composeChanges();composeWeakness();composeStorage();composeEvidence();composeActions();composeGenericViews();}
  function applyDesktopNames(){for(const [view,meta] of Object.entries(IA)){const button=q(document,`.nav[data-view="${view}"]`);if(button&&button.textContent!==meta.nav)button.textContent=meta.nav;}const active=q(document,'.view.active')?.id||'overview',meta=IA[active];if(!meta)return;setText('#pageTitle',meta.title);setText('#pageSub',meta.sub);const section=document.getElementById(active),stage=q(section,':scope > .workspace-intro .workspace-stage'),question=q(section,':scope > .workspace-intro .workspace-question');if(stage)stage.textContent=meta.stage;if(question)question.textContent=meta.question;}

  installNavigation();rewriteStaticCopy();rewriteEmptyStates();relabelButtons();composeAllViews();applyDesktopNames();
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installNavigation();rewriteStaticCopy();rewriteEmptyStates();relabelButtons();composeAllViews();applyDesktopNames();},{once:true});
  const app=q(document,'.app');if(app){const observer=new MutationObserver(records=>{if(records.some(r=>r.type==='attributes'&&r.attributeName==='class'))queueMicrotask(applyDesktopNames);});observer.observe(app,{subtree:true,attributes:true,attributeFilter:['class']});}

  const endpointRules=[['/api/system-profile','hardware','Reading machine'],['/api/quick-check','quickcheck','Building snapshot'],['/api/review-queue','quickcheck','Building review queue'],['/api/guided-snapshot','quickcheck','Capturing evidence'],['/api/readiness','overview','Verifying Sentinel'],['/api/search/deep','weakness','Searching filenames'],['/api/weakness-audit','weakness','Auditing visibility'],['/api/coverage','weakness','Reading coverage'],['/api/advanced-sensor/status','weakness','Checking sensor boundary'],['/api/search','weakness','Searching evidence'],['/api/changes','changes','Updating watch'],['/api/incidents','incidents','Building cases'],['/api/storage','storage','Measuring storage'],['/api/security/audit','security','Running evidence audit'],['/api/self/integrity','overview','Verifying Sentinel binary'],['/api/integrity','integrity','Verifying object'],['/api/intelligence','intelligence','Building relationships'],['/api/object/story','intelligence','Building object narrative'],['/api/behavior','behavior','Comparing behavior'],['/api/trust','trust','Comparing reference'],['/api/process/detail','processes','Inspecting process'],['/api/processes','processes','Loading processes'],['/api/startup','startup','Loading startup'],['/api/persistence','persistence','Comparing persistence'],['/api/background','background','Loading background'],['/api/network','network','Loading network'],['/api/cleanup/preview','cleanup','Analyzing reclaimable space'],['/api/actions','actions','Preparing reversible action'],['/api/report/export','overview','Building evidence report'],['/api/diagnostics/export','overview','Building diagnostics'],['/api/capabilities','overview','Checking evidence sources'],['/api/overview','overview','Refreshing command view']];
  const panelState=new WeakMap();
  function stateFor(panel){let state=panelState.get(panel);if(!state){state={active:0,percent:0,timer:null};panelState.set(panel,state);}return state;}
  function panelForView(viewId){const view=document.getElementById(viewId)||q(document,'.view.active');if(!view)return null;let panel=q(view,'.sentinel-task-progress');if(panel)return panel;const host=q(view,'.workspace-intro')||q(view,'.card')||view;panel=make('div','sentinel-task-progress');panel.dataset.state='idle';const head=make('div','sentinel-progress-head');head.append(make('b','','Ready'),make('strong','','0%'));const bar=document.createElement('progress');bar.className='sentinel-percent-bar';bar.max=100;bar.value=0;panel.append(head,bar,make('small','sentinel-progress-detail','Progress appears when a localhost evidence request starts.'));host.appendChild(panel);return panel;}
  function setPanel(panel,percent,label,detail,stateName='running'){if(!panel)return;const value=Math.max(0,Math.min(100,Math.round(Number(percent)||0))),state=stateFor(panel);state.percent=value;panel.dataset.state=stateName;const head=q(panel,'.sentinel-progress-head'),b=q(head,'b'),strong=q(head,'strong'),bar=q(panel,'.sentinel-percent-bar'),small=q(panel,'.sentinel-progress-detail');if(b)b.textContent=label;if(strong)strong.textContent=`${value}%`;if(bar)bar.value=value;if(small)small.textContent=detail||'';}
  function stopTimer(panel){const state=stateFor(panel);if(state.timer)clearInterval(state.timer);state.timer=null;}
  function requestInfo(input){try{const raw=typeof input==='string'?input:(input?.url||''),url=new URL(raw,location.origin),match=endpointRules.find(([prefix])=>url.pathname.startsWith(prefix));return{path:url.pathname,view:match?.[1]||q(document,'.view.active')?.id||'overview',label:match?.[2]||'Working locally'};}catch{return{path:'',view:q(document,'.view.active')?.id||'overview',label:'Working locally'};}}
  function beginRequest(info){const panel=panelForView(info.view);if(!panel)return null;const state=stateFor(panel);state.active+=1;if(state.active===1){const start=state.percent>=100?8:Math.max(8,state.percent||8);setPanel(panel,start,info.label,`${info.path} · local evidence request started.`,'running');state.timer=setInterval(()=>{const next=Math.min(92,state.percent+(state.percent<45?4:1));setPanel(panel,next,info.label,'Waiting for the local Sentinel engine.','running');},450);}return panel;}
  const storagePhaseLabel=phase=>({walking:'Scanning files',grouping:'Preparing duplicate candidates',hashing:'Hashing duplicate candidates',finalizing:'Building storage report',complete:'Storage scan complete',cancelled:'Storage scan cancelled',failed:'Storage scan failed'}[phase]||'Scanning storage');
  const formatBytes=value=>{let n=Math.max(0,Number(value)||0);const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i+=1;}return`${n.toFixed(i===0||n>=10?1:2)} ${units[i]}`;};
  function handleStorageJob(job){if(!job||typeof job!=='object')return;const panel=panelForView('storage');if(!panel)return;const phase=String(job.phase||job.status||'walking'),percent=Number(job.phase_percent||(job.status==='complete'?100:12)),files=Number(job.files_visited||0),dirs=Number(job.dirs_visited||0),slow=Number(job.slow_paths_skipped||0),hashFilesDone=Number(job.hash_files_done||0),hashFilesTotal=Number(job.hash_files_total||0),hashBytesDone=Number(job.hash_bytes_done||0),hashBytesTotal=Number(job.hash_bytes_total||0),currentHashPath=String(job.current_hash_path||''),bits=[`${files.toLocaleString()} files`,`${dirs.toLocaleString()} folders`,`${slow.toLocaleString()} slow paths skipped`];if(phase==='hashing'||hashFilesTotal>0||hashBytesTotal>0){bits.push(`${hashFilesDone.toLocaleString()}/${hashFilesTotal.toLocaleString()} hash files`);bits.push(`${formatBytes(hashBytesDone)} / ${formatBytes(hashBytesTotal)} hashed`);if(currentHashPath)bits.push(currentHashPath);}const stateName=job.status==='failed'?'error':job.status==='complete'?'complete':'running';setPanel(panel,percent,storagePhaseLabel(phase),bits.join(' · '),stateName);}

  const nativeFetch=window.fetch.bind(window);
  window.fetch = async (...args)=>{const info=requestInfo(args[0]),panel=beginRequest(info);try{const response=await nativeFetch(...args);let payload=null;try{const type=response.headers.get('content-type')||'';if(type.includes('application/json'))payload=await response.clone().json();}catch{payload=null;}if(payload&&info.path.startsWith('/api/storage'))handleStorageJob(payload);if(panel){const state=stateFor(panel);state.active=Math.max(0,state.active-1);if(state.active===0){stopTimer(panel);if(!payload||!info.path.startsWith('/api/storage')||payload.status!=='running'){setPanel(panel,100,response.ok?`${info.label} complete`:`${info.label} failed`,response.ok?'Evidence updated from the local engine.':`Local request failed: HTTP ${response.status}`,response.ok?'complete':'error');}}}return response;}catch(error){if(panel){stopTimer(panel);const state=stateFor(panel);state.active=0;setPanel(panel,100,`${info.label} failed`,`Local request failed: ${error?.message||error}`,'error');}throw error;}};
  window.addEventListener('error',event=>{const panel=panelForView(q(document,'.view.active')?.id||'overview');if(panel)setPanel(panel,100,'Interface error',`Interface error: ${event.message||'Unknown desktop UI error'}`,'error');});
  window.addEventListener('unhandledrejection',event=>{const panel=panelForView(q(document,'.view.active')?.id||'overview'),detail=event.reason?.message||String(event.reason||'Unknown rejection');if(panel)setPanel(panel,100,'Interface error',`Interface error: ${detail}`,'error');});
})();
