// SPDX-License-Identifier: MPL-2.0
(() => {
  const token = new URLSearchParams(location.hash.slice(1)).get('token') || '';
  const $ = id => document.getElementById(id);
  const el = (tag, cls='', text='') => { const n=document.createElement(tag); if(cls)n.className=cls; if(text!=='')n.textContent=String(text); return n; };
  const i18n=window.SentinelI18n;
  i18n.register({
    en:{
      'easy.metric.security':'Security review','easy.metric.incidents':'Active incidents','easy.metric.system':'System snapshots','easy.metric.storage':'Storage history','easy.metric.actions':'Recoverable actions','easy.metric.vault':'Vault items','easy.metric.network':'Network snapshots','easy.metric.delta':'Latest storage delta','easy.metric.none':'No retained signal','easy.metric.signals':'{n} signal(s)',
      'easy.card.security':'Security','easy.card.incidents':'Incidents','easy.card.disk':'Disk pressure','easy.card.recovery':'Recovery state','easy.card.vault':'Vault isolation','easy.card.behavior':'Behavior baseline','easy.card.trust':'Trusted profile','easy.card.persistence':'Persistence baseline','easy.card.changes':'Change monitor','easy.card.visibility':'Evidence visibility',
      'easy.recommendations':'Recommended next steps','easy.checked':'Checked {time}. Attention Index {score} ({band}). This is a bounded read-only review, not a safety certificate.','easy.nochange':'No automatic system change was made.','easy.failed':'One-click Check could not complete: {error}',
      'easy.security.detail':'{n} current finding(s). This score prioritizes review; it is not malware probability.','easy.incident.high':'{n} high-priority incident(s) are currently retained.','easy.incident.none':'No active incident story is currently retained.','easy.disk.review':'Disk usage is high enough to deserve a bounded storage review.','easy.disk.ok':'Current disk usage is below the Easy review threshold.','easy.recovery.ok':'Vault and Safe Action recovery metadata passed the current self-health checks.','easy.recovery.review':'Vault or Safe Action recovery metadata reported a health issue.','easy.vault.failed':'{n} Vault item(s) failed a live isolation check.','easy.vault.partial':'{n} Vault item(s) are only partially contained or have an unverified isolation property.','easy.vault.full':'All active Vault items passed the bounded live containment checks.','easy.vault.none':'There are no active Vault objects to verify.','easy.vault.value':'{full}/{total} fully contained','easy.behavior.value':'Latest behavior index: {n}.','easy.behavior.none':'Optional baseline is not present; Easy does not create one automatically.','easy.trust.value':'Latest trust drift index: {n}.','easy.trust.none':'Optional user-approved Trusted Profile is not present.','easy.persistence.high':'{n} high-severity persistence change(s) are retained.','easy.persistence.ok':'No high-severity persistence change is reported by this quick check.','easy.persistence.none':'Optional persistence comparison baseline is not present.','easy.change.rescan':'Incremental change evidence should not be treated as complete until a rescan.','easy.change.running':'A focused filesystem change watch is active.','easy.change.stopped':'Change Monitor is optional and currently stopped.','easy.visibility.review':'Some local evidence sources are unavailable; Sentinel reduces visibility instead of inventing results.','easy.visibility.ok':'No unavailable evidence source was reported by this quick check.'
    },
    'zh-CN':{
      'easy.metric.security':'安全检查','easy.metric.incidents':'活动事件','easy.metric.system':'系统快照','easy.metric.storage':'存储历史','easy.metric.actions':'可恢复操作','easy.metric.vault':'Vault 项目','easy.metric.network':'网络快照','easy.metric.delta':'最新存储变化','easy.metric.none':'没有保留信号','easy.metric.signals':'{n} 个信号',
      'easy.card.security':'安全','easy.card.incidents':'事件','easy.card.disk':'磁盘压力','easy.card.recovery':'恢复状态','easy.card.vault':'Vault 隔离','easy.card.behavior':'行为基线','easy.card.trust':'可信配置','easy.card.persistence':'持久化基线','easy.card.changes':'变更监控','easy.card.visibility':'证据可见性',
      'easy.recommendations':'建议的下一步','easy.checked':'检查时间 {time}。Attention Index {score}（{band}）。这是有界只读检查，不是安全证明。','easy.nochange':'没有执行任何自动系统修改。','easy.failed':'一键检查未能完成：{error}',
      'easy.security.detail':'当前有 {n} 个发现。该分数只用于安排检查优先级，不代表恶意软件概率。','easy.incident.high':'当前保留 {n} 个高优先级事件。','easy.incident.none':'当前没有保留活动事件故事。','easy.disk.review':'磁盘占用已经达到值得进行有界存储检查的水平。','easy.disk.ok':'当前磁盘占用低于 Easy 的检查阈值。','easy.recovery.ok':'Vault 与 Safe Action 恢复元数据通过当前自检。','easy.recovery.review':'Vault 或 Safe Action 恢复元数据报告了需要检查的问题。','easy.vault.failed':'有 {n} 个 Vault 项目未通过实时隔离检查。','easy.vault.partial':'有 {n} 个 Vault 项目只达到部分隔离，或存在尚未验证的隔离属性。','easy.vault.full':'所有活动 Vault 项目都通过了当前有界实时隔离检查。','easy.vault.none':'当前没有需要验证的活动 Vault 对象。','easy.vault.value':'{full}/{total} 完全隔离','easy.behavior.value':'最新行为指数：{n}。','easy.behavior.none':'尚未建立可选行为基线；Easy 不会自动创建。','easy.trust.value':'最新可信漂移指数：{n}。','easy.trust.none':'尚未建立需要用户确认的 Trusted Profile。','easy.persistence.high':'保留了 {n} 个高严重度持久化变化。','easy.persistence.ok':'本次快速检查没有报告高严重度持久化变化。','easy.persistence.none':'尚未建立可选持久化比较基线。','easy.change.rescan':'在重新扫描之前，不应把增量变更证据当作完整证据。','easy.change.running':'当前正在运行一个聚焦的文件系统变更监控。','easy.change.stopped':'Change Monitor 是可选功能，目前已停止。','easy.visibility.review':'部分本地证据源不可用；Sentinel 会降低可见性，而不是编造结果。','easy.visibility.ok':'本次快速检查没有报告不可用证据源。'
    }
  });
  const t=(key,vars)=>i18n.t(key,vars);
  const metric = (label,value) => { const n=el('div','metric'); n.append(el('span','',label),el('b','',value)); return n; };
  const fmtBytes = n => { const raw=Number(n||0),sign=raw<0?'-':raw>0?'+':'';let v=Math.abs(raw),u=['B','KB','MB','GB','TB'],i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${sign}${v.toFixed(i>1?1:0)} ${u[i]}`; };
  async function api(url, options={}) { options.headers={...(options.headers||{}),'X-Sentinel-Token':token}; const r=await fetch(url,options); const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`); return d; }
  const postMode = mode => api(`/api/system/query/structured?mode=${encodeURIComponent(mode)}`,{method:'POST'});
  const viewPath=view=>({security:'/security-center.html',incidents:'/intelligence-center.html',storage:'/storage-center.html',behavior:'/intelligence-center.html',trust:'/intelligence-center.html',persistence:'/launch-services.html',actions:'/vault-health.html',changes:'/system-center.html',weakness:'/intelligence-center.html',overview:'/easy.html'}[view]||'/easy.html');
  const withToken=path=>`${path}#token=${encodeURIComponent(token)}`;
  function wireLinks(){for(const a of document.querySelectorAll('[data-path]'))a.href=withToken(a.dataset.path);for(const a of document.querySelectorAll('.hero-actions a')){const u=new URL(a.getAttribute('href'),location.origin);a.href=withToken(u.pathname);}}
  let latestOverview=null,latestQuick=null,latestIsolation=null;

  function render(security,recovery,system,storage){latestOverview={security,recovery,system,storage};const box=$('easyStatus');box.replaceChildren(
    metric(t('easy.metric.security'),(security.review_signals||[]).length?t('easy.metric.signals',{n:(security.review_signals||[]).length}):t('easy.metric.none')),
    metric(t('easy.metric.incidents'),security.active_incidents||0),metric(t('easy.metric.system'),(system.snapshots||[]).length),metric(t('easy.metric.storage'),(storage.snapshots||[]).length),metric(t('easy.metric.actions'),recovery.recoverable_actions||0),metric(t('easy.metric.vault'),(recovery.vault||[]).length),metric(t('easy.metric.network'),recovery.network_snapshots||0),metric(t('easy.metric.delta'),storage.has_comparison?fmtBytes(storage.latest_comparison?.delta_bytes):'—'));
    const notes=[];if((security.review_signals||[]).length)notes.push(i18n.getLocale()==='zh-CN'?'安全模块保留了需要检查的信号。':'Security has retained review signals.');if(recovery.advisories?.length)notes.push(i18n.getLocale()==='zh-CN'?`${recovery.advisories.length} 个恢复建议。`:`${recovery.advisories.length} recovery advisory item(s).`);if(!notes.length)notes.push(i18n.getLocale()==='zh-CN'?'当前没有保留的检查/建议信号；缺失证据永远不能被当作安全证明。':'No retained review/advisory signal is currently reported; missing evidence is never treated as proof of safety.');$('statusNote').textContent=notes.join(' ');
  }

  function checkCard(titleKey, state, value, detail, path) {
    const card=el('article',`check-card ${state}`);const head=el('div','check-card-head');
    head.append(el('b','',t(titleKey)),el('span',`check-state ${state}`,state==='good'?t('common.ok'):state==='bad'?t('common.failed'):state==='review'?t('common.review'):t('common.info')));
    card.append(head,el('strong','check-value',value),el('p','',detail));
    const actions=el('div','check-card-actions');const why=el('span','check-why',t('common.why'));why.title=detail;actions.append(why);if(path){const a=el('a','',t('common.continue'));a.href=withToken(path);actions.append(a);}card.append(actions);return card;
  }
  function renderRecommendations(q){const root=$('oneClickRecommendations');root.replaceChildren();const rows=Array.isArray(q?.recommendations)?q.recommendations:[];if(!rows.length)return;const title=el('h3','',t('easy.recommendations'));root.append(title);for(const r of rows.slice(0,5)){const card=el('div','easy-recommendation');const text=el('div');text.append(el('b','',r.title||'Recommendation'),el('p','',r.reason||''));card.append(text);const a=el('a','',r.cta||t('common.continue'));a.href=withToken(viewPath(r.view));card.append(a);root.append(card);}}

  function renderOneClick(q, isolation) {latestQuick=q;latestIsolation=isolation;const root=$('oneClickResults');const secScore=Number(q?.security?.score||0),secFindings=Array.isArray(q?.security?.findings)?q.security.findings.length:0;const incidentHigh=Number(q?.incident_high||0),incidentCount=Number(q?.incident_count||0);const disk=Number(q?.disk_percent||0),actionHealthy=Boolean(q?.action_health?.healthy),missing=Array.isArray(q?.missing_evidence)?q.missing_evidence.length:0,change=q?.change_monitor||{};const cards=[];
    cards.push(checkCard('easy.card.security',secScore>=70?'bad':secScore>=40?'review':'good',`${secScore}/100`,t('easy.security.detail',{n:secFindings}),'/security-center.html'));
    cards.push(checkCard('easy.card.incidents',incidentHigh>0?'bad':incidentCount>0?'review':'good',String(incidentCount),incidentCount?t('easy.incident.high',{n:incidentHigh}):t('easy.incident.none'),'/intelligence-center.html'));
    cards.push(checkCard('easy.card.disk',disk>=95?'bad':disk>=85?'review':'good',`${disk}%`,disk>=85?t('easy.disk.review'):t('easy.disk.ok'),'/storage-center.html'));
    cards.push(checkCard('easy.card.recovery',actionHealthy?'good':'review',actionHealthy?t('common.healthy'):t('common.needsReview'),actionHealthy?t('easy.recovery.ok'):t('easy.recovery.review'),'/vault-health.html'));
    const failed=Number(isolation?.isolation_failed||0),partial=Number(isolation?.partially_contained||0),full=Number(isolation?.fully_contained||0),total=Array.isArray(isolation?.items)?isolation.items.length:0;const vaultState=failed>0?'bad':partial>0?'review':'good';const vaultValue=total?t('easy.vault.value',{full,total}):t('common.noActiveItems');const vaultDetail=failed?t('easy.vault.failed',{n:failed}):partial?t('easy.vault.partial',{n:partial}):total?t('easy.vault.full'):t('easy.vault.none');cards.push(checkCard('easy.card.vault',vaultState,vaultValue,vaultDetail,'/vault-health.html'));
    cards.push(checkCard('easy.card.behavior',q?.behavior_baseline?(Number(q?.behavior_index||0)>=30?'review':'good'):'info',q?.behavior_baseline?(q?.behavior_band||'Captured'):t('common.notCaptured'),q?.behavior_baseline?t('easy.behavior.value',{n:Number(q?.behavior_index||0)}):t('easy.behavior.none'),'/intelligence-center.html'));
    cards.push(checkCard('easy.card.trust',q?.trust_profile?(Number(q?.trust_index||0)>=30?'review':'good'):'info',q?.trust_profile?(q?.trust_band||'Compared'):t('common.notCaptured'),q?.trust_profile?t('easy.trust.value',{n:Number(q?.trust_index||0)}):t('easy.trust.none'),'/intelligence-center.html'));
    cards.push(checkCard('easy.card.persistence',Number(q?.persistence_high||0)>0?'review':q?.persistence_baseline?'good':'info',q?.persistence_baseline?t('common.ready'):t('common.notCaptured'),Number(q?.persistence_high||0)>0?t('easy.persistence.high',{n:Number(q.persistence_high)}):q?.persistence_baseline?t('easy.persistence.ok'):t('easy.persistence.none'),'/launch-services.html'));
    cards.push(checkCard('easy.card.changes',change.needs_rescan?'review':change.running?'good':'info',change.needs_rescan?(i18n.getLocale()==='zh-CN'?'需要重新扫描':'Rescan needed'):change.running?t('common.running'):t('common.stopped'),change.needs_rescan?t('easy.change.rescan'):change.running?t('easy.change.running'):t('easy.change.stopped'),'/system-center.html'));
    cards.push(checkCard('easy.card.visibility',missing?'review':'good',missing?(i18n.getLocale()==='zh-CN'?`${missing} 个受限来源`:`${missing} limited source(s)`):t('common.available'),missing?t('easy.visibility.review'):t('easy.visibility.ok'),'/intelligence-center.html'));
    root.replaceChildren(...cards);renderRecommendations(q);const stamp=q?.generated_at?new Date(q.generated_at).toLocaleString():(i18n.getLocale()==='zh-CN'?'刚刚':'just now');$('oneClickNote').textContent=t('easy.checked',{time:stamp,score:Number(q?.attention_index||0),band:q?.band||'Unknown'});
  }
  async function loadOverview(){const [s,r,sys,st]=await Promise.all([postMode('security-posture'),postMode('recovery'),postMode('system-snapshots'),postMode('storage-history')]);render(s,r,sys,st);}
  async function runOneClickCheck(){const button=$('oneClickCheck');button.disabled=true;button.textContent=t('common.checking');$('notice').textContent='';try{const [q,isolation]=await Promise.all([api('/api/quick-check'),api('/api/actions/vault/isolation'),loadOverview()]).then(([quick,vault])=>[quick,vault]);renderOneClick(q,isolation);}catch(e){$('notice').textContent=t('easy.failed',{error:e.message});$('oneClickNote').textContent=t('easy.nochange');}finally{button.disabled=false;button.textContent=t('easy.quick.title');}}
  wireLinks();if(!token){$('notice').textContent='Missing Sentinel session token. Open Easy from the running Sentinel app.';return;}$('oneClickCheck').addEventListener('click',runOneClickCheck);document.addEventListener('sentinel:localechange',()=>{wireLinks();if(latestOverview)render(latestOverview.security,latestOverview.recovery,latestOverview.system,latestOverview.storage);if(latestQuick&&latestIsolation)renderOneClick(latestQuick,latestIsolation);else $('oneClickCheck').textContent=t('easy.quick.title');});loadOverview().catch(e=>{$('notice').textContent=e.message;$('statusNote').textContent='Some Easy overview evidence could not be loaded.';});
})();
