// SPDX-License-Identifier: MPL-2.0
(() => {
  const token = new URLSearchParams(location.hash.slice(1)).get('token') || '';
  const workspace = document.body.dataset.workspace || '';
  const $ = id => document.getElementById(id);
  const el = (tag, cls = '', text = '') => { const n=document.createElement(tag); if(cls)n.className=cls; if(text!=='')n.textContent=String(text); return n; };
  const notice = text => { const n=$('notice'); if(n)n.textContent=text || ''; };
  const fmtTime = s => { if(!s)return '—'; const d=typeof s==='number'?new Date(s*1000):new Date(s); return Number.isNaN(d.valueOf())?String(s):d.toLocaleString(); };
  const fmtBytes = n => { let v=Number(n||0),a=Math.abs(v),u=['B','KB','MB','GB','TB'],i=0; while(a>=1024&&i<u.length-1){a/=1024;i++;} return `${v<0?'-':''}${a.toFixed(i>1?1:0)} ${u[i]}`; };
  const metric = (label,value) => { const n=el('div','metric'); n.append(el('span','',label),el('b','',value)); return n; };
  const badge = (text,kind='') => el('span',`badge ${kind}`,text);
  const tokenHref = (path, extra='') => `${path}#token=${encodeURIComponent(token)}${extra}`;
  const investigate = path => { const a=el('a','','Investigate'); a.href=tokenHref('/investigation.html',`&path=${encodeURIComponent(path)}`); return a; };
  function wireWorkspaceLinks(){for(const a of document.querySelectorAll('.hero-actions a')){const u=new URL(a.getAttribute('href'),location.origin);a.href=`${u.pathname}${u.search}#token=${encodeURIComponent(token)}`;}}

  async function api(url, options={}) {
    options.headers={...(options.headers||{}),'X-Sentinel-Token':token};
    const r=await fetch(url,options); const d=await r.json().catch(()=>({error:`HTTP ${r.status}`}));
    if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`); return d;
  }
  function modeURL(mode, params={}) { return `/api/system/query/structured?${new URLSearchParams({mode,...params}).toString()}`; }
  const postMode=(mode,params={})=>api(modeURL(mode,params),{method:'POST'});
  const runTool=(tool_id,target='')=>api('/api/system/query/structured',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool_id,target})});

  function renderSecurity(data){
    const summary=$('securitySummary'); if(summary) summary.replaceChildren(
      metric('Typed sources',(data.latest_evidence||[]).length),
      metric('Review signals',(data.review_signals||[]).length),
      metric('Incident eligible',data.incident_eligible||0),
      metric('Active incidents',data.active_incidents||0),
      metric('Safe Actions',data.safe_actions?.healthy?'healthy':'review')
    );
    const evidence=$('securityEvidence'); if(evidence){evidence.replaceChildren(); for(const row of data.latest_evidence||[]){const c=el('article','card');c.append(el('h3','',row.tool_name||row.tool_id),el('p','',row.summary||row.status||'Observed'),el('small','',`${fmtTime(row.at)}${row.target?` · ${row.target}`:''}`));for(const s of row.signals||[])c.append(badge(s.summary||s.code,s.severity||''));if(row.target?.startsWith('/')){const a=el('div','row-actions');a.append(investigate(row.target));c.append(a);}evidence.append(c);}if(!(data.latest_evidence||[]).length)evidence.append(el('p','help','No retained typed security evidence yet. Refresh to query the fixed local security sources.'));}
    const signals=$('securitySignals'); if(signals){signals.replaceChildren(); for(const s of data.review_signals||[]){const row=el('div','row'),main=el('div','row-main'),actions=el('div','row-actions');main.append(badge(s.severity||'review',s.severity||'review'),el('b','',s.summary||s.code),el('p','',s.detail||'Typed review signal.'));const open=el('a','','Open Incidents');open.href=`/intelligence-center.html?section=incidents#token=${encodeURIComponent(token)}`;actions.append(open);row.append(main,actions);signals.append(row);}if(!(data.review_signals||[]).length)signals.append(el('p','help','No retained typed review signal is currently present. Missing evidence is not proof of safety.'));}
  }
  async function refreshSecurity(){const b=$('refreshSecurity');if(b)b.disabled=true;notice('Refreshing bounded security evidence…');try{await Promise.all(['gatekeeper-status','filevault-status','sip-status','system-extensions'].map(id=>runTool(id).catch(()=>null)));renderSecurity(await postMode('security-posture'));notice('Security Center refreshed.');}catch(e){notice(e.message)}finally{if(b)b.disabled=false;}}

  function fillSnapshotSelects(rows){for(const id of ['snapshotFrom','snapshotTo']){const s=$(id);if(s)s.replaceChildren();}rows.forEach((snap,i)=>{for(const id of ['snapshotFrom','snapshotTo']){const s=$(id);if(!s)continue;const o=el('option','',`${fmtTime(snap.captured_at)}${snap.partial?' · partial':''}`);o.value=snap.id;s.append(o);}if(i===0&&$('snapshotTo'))$('snapshotTo').value=snap.id;if(i===1&&$('snapshotFrom'))$('snapshotFrom').value=snap.id;});}
  function renderSnapshots(data){const rows=data.snapshots||[];fillSnapshotSelects(rows);const box=$('snapshotList');if(!box)return;box.replaceChildren();for(const s of rows){const row=el('div','row'),main=el('div','row-main');main.append(el('b','',fmtTime(s.captured_at)),el('p','',`${(s.processes||[]).length} processes · ${(s.startup||[]).length} startup · ${(s.network||[]).length} TCP · ${(s.mounts||[]).length} mounts`),badge(s.partial?'partial evidence':'selected sources complete',s.partial?'review':'ok'));for(const l of s.limitations||[])main.append(el('small','',`Limitation: ${l}`));row.append(main);box.append(row);}if(!rows.length)box.append(el('p','help','No retained System Snapshot yet. Capture is explicit and bounded to 16.'));}
  async function loadSnapshots(){renderSnapshots(await postMode('system-snapshots'));}
  async function captureSnapshot(){const b=$('captureSnapshot');if(b)b.disabled=true;notice('Capturing selected current macOS evidence…');try{await postMode('system-snapshot-capture');await loadSnapshots();notice('System Snapshot captured.');}catch(e){notice(e.message)}finally{if(b)b.disabled=false;}}
  function renderSnapshotDiff(diff){const box=$('snapshotDiff');if(!box)return;box.replaceChildren();const top=el('div','row'),main=el('div','row-main');main.append(el('b','',`${fmtTime(diff.from_at)} → ${fmtTime(diff.to_at)}`),el('p','',`${diff.change_count||0} observed differences.`));top.append(main);box.append(top);for(const c of diff.categories||[]){const group=el('div','card diff-group');group.append(el('h3','',c.category));for(const x of c.added||[])group.append(el('p','delta-positive',`+ ${x}`));for(const x of c.removed||[])group.append(el('p','delta-negative',`− ${x}`));box.append(group);}for(const [key,pair] of Object.entries(diff.security_changed||{})){const group=el('div','card diff-group');group.append(el('h3','',`Security · ${key}`),el('p','',`${pair?.[0]||'—'} → ${pair?.[1]||'—'}`));box.append(group);}box.append(el('p','help',diff.note||'Snapshot differences are observations, not causal conclusions.'));}
  async function compareSnapshots(){const from=$('snapshotFrom')?.value,to=$('snapshotTo')?.value;if(!from||!to){notice('Capture at least two snapshots to compare.');return;}try{renderSnapshotDiff(await postMode('system-snapshot-diff',{from,to}));notice('Snapshot comparison updated.');}catch(e){notice(e.message)}}
  function renderSystemEvidence(data){const box=$('systemEvidence');if(!box)return;box.replaceChildren();for(const e of data.rows||[]){const row=el('div','row'),main=el('div','row-main'),actions=el('div','row-actions');main.append(el('b','',e.tool_name||e.tool_id),el('p','',e.summary||e.status||''),el('small','',`${fmtTime(e.at)}${e.target?` · ${e.target}`:''}`));for(const s of e.signals||[])main.append(badge(s.code||s.summary,s.severity||''));if(e.target?.startsWith('/'))actions.append(investigate(e.target));row.append(main,actions);box.append(row);}if(!(data.rows||[]).length)box.append(el('p','help','No retained typed System Console evidence yet.'));}
  async function loadSystemEvidence(){renderSystemEvidence(await postMode('system-evidence'));}

  function renderStorage(data){const snaps=data.snapshots||[],cmp=data.latest_comparison||{};const summary=$('storageSummary');if(summary)summary.replaceChildren(metric('Retained snapshots',snaps.length),metric('Retention',data.retention||24),metric('Mode',data.persistent?'persistent':'memory-only'),metric('Latest delta',data.has_comparison?fmtBytes(cmp.delta_bytes):'—'),metric('Latest root',cmp.root||snaps.at(-1)?.root||'—'));const box=$('storageHistory');if(!box)return;box.replaceChildren();if(data.has_comparison){const c=el('div','card');c.append(el('h3','',`Latest growth · ${fmtBytes(cmp.delta_bytes)}`),el('p','',`${fmtTime(cmp.before_at)} → ${fmtTime(cmp.after_at)}`));for(const d of (cmp.directory_changes||[]).slice(0,12))c.append(el('p',d.delta_bytes>=0?'delta-positive':'delta-negative',`${d.delta_bytes>=0?'+':''}${fmtBytes(d.delta_bytes)} · ${d.name}`));if(cmp.partial)c.append(badge('partial comparison','review'));box.append(c);}for(const s of [...snaps].reverse().slice(0,12)){const row=el('div','row'),main=el('div','row-main'),actions=el('div','row-actions');main.append(el('b','',fmtTime(s.created_at)),el('p','',`${s.root||'unknown root'} · ${fmtBytes(s.visible_bytes)} · ${s.files_visited||0} files`),badge(s.partial?'partial':'captured',s.partial?'review':'ok'));if(s.root?.startsWith('/'))actions.append(investigate(s.root));row.append(main,actions);box.append(row);}if(!snaps.length)box.append(el('p','help','No Storage History snapshot yet. Run Storage Intelligence, then capture its completed result.'));}
  async function loadStorage(){renderStorage(await postMode('storage-history'));}
  async function captureStorage(){const b=$('captureStorage');if(b)b.disabled=true;notice('Capturing latest completed Storage Intelligence result…');try{await postMode('storage-snapshot-capture');await loadStorage();notice('Storage snapshot captured.');}catch(e){notice(e.message)}finally{if(b)b.disabled=false;}}
  function renderAging(data){const summary=$('storageAgingSummary'),box=$('storageAging');if(!summary||!box)return;summary.replaceChildren(metric('Large files considered',data.files_considered||0),metric('Bytes considered',fmtBytes(data.bytes_considered)),metric('Age buckets',(data.buckets||[]).length),metric('Trend points',(data.trend||[]).length));box.replaceChildren();for(const b of data.buckets||[]){const row=el('div','row'),main=el('div','row-main');main.append(el('b','',b.label),el('p','',`${b.files||0} retained large file(s) · ${fmtBytes(b.bytes)}`));row.append(main);box.append(row);}for(const f of (data.oldest_large_files||[]).slice(0,30)){const row=el('div','row'),main=el('div','row-main'),actions=el('div','row-actions');main.append(el('b','',`${f.age_days} days · ${f.name||f.path}`),el('p','',`${fmtBytes(f.size)} · ${f.path}`));if(String(f.path||'').startsWith('/'))actions.append(investigate(f.path));row.append(main,actions);box.append(row);}for(const l of data.limitations||[])box.append(el('p','help',`Limitation: ${l}`));if(data.note)box.append(el('p','help',data.note));}
  async function loadAging(){const b=$('refreshStorageAging');if(b)b.disabled=true;try{renderAging(await api('/api/storage/aging'));}catch(e){notice(e.message)}finally{if(b)b.disabled=false;}}

  wireWorkspaceLinks();
  if(!token){notice('Missing Sentinel session token. Open this workspace from the running Sentinel app.');return;}
  if(workspace==='security'){$('refreshSecurity')?.addEventListener('click',refreshSecurity);postMode('security-posture').then(renderSecurity).catch(e=>notice(e.message));}
  if(workspace==='system'){$('captureSnapshot')?.addEventListener('click',captureSnapshot);$('compareSnapshots')?.addEventListener('click',compareSnapshots);$('refreshEvidence')?.addEventListener('click',()=>loadSystemEvidence().catch(e=>notice(e.message)));Promise.all([loadSnapshots(),loadSystemEvidence()]).catch(e=>notice(e.message));}
  if(workspace==='storage'){$('captureStorage')?.addEventListener('click',captureStorage);$('refreshStorageAging')?.addEventListener('click',loadAging);Promise.all([loadStorage(),loadAging()]).catch(e=>notice(e.message));}
})();
